[tool.poetry]
name = "facilitycalc"
version = "0.1.0"
description = "Foxhole Facility Calculator"
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "FacilityCalc", from = ".."}]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"
mypy = "^1.8.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = "."
testpaths = ["tests"]

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true
